### PR TITLE
News week clone (Milestone 2)

### PR DESCRIPTION
**Pull request by hamdiheb**
We've been working on Newsweek website clone using responsive design for Project 2: Building with Bootstrap Design - Milestone 2.
This branch in the repository includes the next files:

index.html
css/index.css/bootstrap.min.css
img folder with all images used for Newsweek website clone.
linters.yml
stylelintrcs.json
.hintrc
README.md
Project license file.
Finally, we've deployed this repository to GitHub pages and we've used GRID bootstrap and added
Column 1  : 
Featured stories
Sponsored insights / Rankings

Column 2 : 
Top story
My turn
Culture & travel
More stories

Column 3 : 
The debate
Opinion
Sponsored insights / Rankings
Free signup

### CODE REVIEW

**Review by mricanho — CHANGES_REQUESTED** [review]
# 🔴  Changes Required 🔴  

Hello @hamdiheb, @fortuneonyeka you did a good job in this milestone🔥, now we need to do a few arrangements:

- [x]  **First of all, you are using a lot of CSS code, the scope of this project is to work with bootstrap and realized how powerful it is. You are using a lot of display: flex, margins, display: none, colors, etc. Please fix that and use bootstrap instead** 
- [x] **You need to add the category names in the featured stories (e.g. US, POLITICS, etc), with the right background and font color**
- [x] **You need to do the same with the Sponsored Insight section, remember, the right background and font color is a must**
- [x] **The second column is totally broken if you set the screen in 1040px, this happens because you have a lot of different width sizes in your elements, check that**
- [x] **In top stories you need to add the category with the right background and font color**
- [x] **Latest stories it's actually latest news**
- [x] **Culture & travel needs the category name**
- [x] **You missed the sponsored insight section, the free sign up and another sponsored insight in the third column**
- [x] **In the tablet version you need margin between your articles in my turn and culture and travel sections**
- [x] **You missed the sponsored insight section, the free sign up and another sponsored insight in the third column for the tablet version** 
- [x] **All the order of the sections is wrong in your mobile version, kindly fix this, you can reorder the sections with [bootstrap](https://getbootstrap.com/docs/4.0/layout/grid/#order-classes)** 

a lot of work

I know that it's a lot, but you can do it! 🥇 

**As described in the [Code reviews limit Policy ](https://microverse.zendesk.com/hc/en-us/articles/1500004088561#)you have 2 code reviews left for this project.**

You can contact me on slack if you have any questions just search for me as @ Miguel Ricaño.

### 💻 👩🏽‍💻  Happy Coding!👨🏽‍💻  🖥️

**Review by mricanho — CHANGES_REQUESTED** [review]
# 🔴  Changes Required 🔴  

Hello @hamdiheb @fortuneonyeka, you actually did some changes since the last time, the order of your website is so much better, good job, now a few fixes are required:

- [x]  **The background of the category names in the featured stories it's actually white with transparency (rgba(255,255,255,.9), kindly fix it** 
- [x] **In featured stories you have an extra title, between the first and the second article, kindly remove it**
- [x] **The same with the sponsored insight, and there the font color it's actually blue([archived website](https://web.archive.org/web/20210120125445/https://www.newsweek.com/))**
- [x] **The problem with the width in the second column persist, all the elements of the second column must have the same width(Top story, My turn, Culture & Travel, etc)**
- [x] **In My turn section, the text must be below the image, right now is side and bellow**
- [x] **In top stories you need to add the category with the right background and font color**
- [x] **Latest stories it's actually latest news, please fix the title**
- [x] **Culture & travel needs the category name too**
- [x] **In the Third Column, the free sign up section comes after the first article of sponsored insight, check the [archived website](https://web.archive.org/web/20210120125445/https://www.newsweek.com/)**
- [x] **The style of the Free Sign Up section it's totally wrong, clone the exact same style(background, layout, padding, etc)**
- [x] **All the third column must have the exact same width and margins between articles(sponsored insight), please fix it**
- [x] **The red Newsweek's ad of the third column(desktop version) overlaps the debate in the mobile version, you can remove the ad of fix the layout**

you can do it

**As described in the[ Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561#) you have only 1 code review left for this project. If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)**

You can contact me on slack if you have any questions just search for me as @ Miguel Ricaño.

### 💻 👩🏽‍💻  Happy Coding!👨🏽‍💻  🖥️

**Review by ElijahTobs — APPROVED** [review]
# Status: Approved! :tada: 

## Congratulations @hamdiheb and @fortuneonyeka :champagne: 

#### You did a really good job implementing all the changes requested by the previous TSE.
#### Below are some optional changes that will make your project appear better:
- [x] `FEATURED STORIES` was misspelt. Kindly see to that.
- [x] The title and short description of the following section have a bootstrap class `pl-x` that is not needed. Kindly discard them.
  - `FEATURED STORIES`
  - TOP STORY
  - MY TURN
  - CULTURE AND TRAVEL

## You can now merge and submit.

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by hamdiheb** [comment]
Thanks to all code reviewers who helped alot in this project

**Pull request merged**
